services:
  sandify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandify
    ports:
      - "3000:3000"
    volumes:
      # Mount only what's needed for development
      - ./:/app
      # Use a named volume for node_modules to avoid overwriting
      - sandify_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    # Enable hot reloading
    stdin_open: true
    tty: true

volumes:
  sandify_node_modules:
